description: >
  This is a sample executor using Docker and Node. If you want to provide a custom environment in your orb, insert your image here.
  If you do not require an executor, you can simply delete this directory.

docker:
  - image: 'cimg/base:<<parameters.tag>>'
parameters:
  tag:
    default: stable
    description: >
      Pick a specific cimg/base image variant:
      https://hub.docker.com/r/cimg/base/tags
    type: string
